### PR TITLE
new PR for fixing a bug

### PR DESCRIPTION
**Pull request by Gabrielvon**
I hope this should be within the scope and passing the test. :)

### CODE REVIEW

**Comment by tsurubee** [comment]
The change was good, but since it will remain in the history of commit, I wanted you to make the new branch from the master.  
https://github.com/tsurubee/banpei/commits/master
Anyway, thank you!

**Comment by Gabrielvon** [comment]
Hi @tsurubee , sorry for the delay. I don't understand. Isn't it merged successfully? I forked this repos and made revision on the forked version. Do you mean I need to copy the branch with revision on my forked version(https://github.com/Gabrielvon/banpei.git) to the branch from the original master(https://github.com/tsurubee/banpei/commits/master)?

**Comment by tsurubee** [comment]
Sorry, my English is not good.  
It merged successfully!

> I forked this repos and made revision on the forked version.

This is OK. Your way of sending PR is correct.
I am talking about commit history.  Please look at the commit history of master branch.   Can you see that unnecessary commits are left as history?  For example, `speed up hotelling.py`

So, when you renewed the PR, you should newly fork the branch again and delete the unnecessary commit.  Can you understand what I am talking about ?

**Comment by Gabrielvon** [comment]
I sort of understood now but likely don't know how to do it. A few questions as follow.
1. If I fork the branch again, will it overwrite my older version? Since I still have on my version which haven't been modified following the rules and merge. 

2. Can remove the unnecessary commit on my older branch and PR again for merging?

Thanks for your patience!

**Comment by tsurubee** [comment]
> If I fork the branch again, will it overwrite my older version?

I think, once you try it, understand it.

If you do not like forking again, you can remove the unnecessary commit by `git revert` commands.

> Can remove the unnecessary commit on my older branch and PR again for merging?

I have already merged it to the master so I can not do it.

**Comment by tsurubee** [comment]
Ref. https://git-scm.com/docs/git-revert

**Comment by Gabrielvon** [comment]
Hey @tsurubee , sorry for the delay. I am so busy recently. I spent a few hours want to figure out how to retreat the commits from the logs of unnecessary commits but I failed. 

I did fork [the branch](https://github.com/tsurubee/banpei.git) again and reverted all unnecessary commits in the results of [this](https://github.com/Gabrielvon/banpei/tree/master). It seems make no effect on the commits that were merged already. 

If you want, I can make another clean PR.

**Comment by tsurubee** [comment]
> If you want, I can make another clean PR.

No, thanks.  
If you have the opportunity to send PR to a repository somewhere, I think that you should pay attention to the above discussed.
Thank you your PR.

**Comment by Gabrielvon** [comment]
> > If you want, I can make another clean PR.
> 
> No, thanks.
> If you have the opportunity to send PR to a repository somewhere, I think that you should pay attention to the above discussed.
> Thank you your PR.

Sure I will. Thanks!

**Pull request merged**
